server:
  port: 8081
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:com.myth.system.mysql.mapper/*.xml,classpath:com.myth.system.mapper/*.xml

spring:
  aop:
    proxy-target-class: true  #true为使用CGLIB代理,AOP动态代理
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.28.171.108:3306/mill
    username: mill
    password: jXWYhHxhBih8cFTB
    dataType: mysql  # 可选值 mysql oracle sqlserver postgresql
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      test-while-idle: false
      validation-query: select 1
  mvc:
    hiddenmethod:
      filter:
        enabled: true
datatype:
  mysql:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{IP}:{port}/{database}
  clickhouse:
    driverClassName: ru.yandex.clickhouse.ClickHouseDriver
    url: jdbc:clickhouse://{IP}:{port}/{database}
  sqlserver:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://{IP}:{port};DatabaseName={database}
  postgresql:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://{IP}:{port}/{database}